import React, { useState, useEffect } from 'react';
import { Download, Copy, Search, LayoutGrid, TrendingUp, Users, Building2, Code2, ShoppingBag, ShieldCheck, Bot } from 'lucide-react';
import ToolSEOContent from '../../components/ToolSEOContent';
import { useCMS } from '../../components/CMSContext';

const RobotsTxtGenerator = () => {
  const { cmsData } = useCMS();
  const toolData = cmsData?.robotsTxtGenerator || {
    toolName: "AI Robots.txt Generator",
    heroTitle: "AI-Optimized Robots.txt Generator",
    heroSubtitle: "Instantly generate an advanced robots.txt file designed for Generative Engine Optimization (GEO) and AI crawler control.",
    steps: [
      { icon: "ShieldCheck", title: "Select Crawlers", description: "Choose which AI bots (Google-Extended, GPTBot, ClaudeBot) to allow or block." },
      { icon: "LayoutGrid", title: "Add Directories", description: "Specify private routes (like /admin) you want to protect from being crawled." },
      { icon: "TrendingUp", title: "Generate File", description: "Download or copy the perfectly formatted robots.txt file." }
    ],
    whatIs: {
      title: "What is an AI-Optimized robots.txt?",
      subtitle: "Taking control of your data in the age of LLMs.",
      p1: "A standard <strong>robots.txt</strong> tells search engines which pages they can crawl. An AI-optimized robots.txt specifically addresses crawlers used by Large Language Models (LLMs) like OpenAI, Anthropic, and Google Gemini.",
      card1Title: "Protect Your Data",
      card1Text: "Block aggressive AI crawlers from scraping your sensitive or paywalled data.",
      card2Title: "Boost AI Visibility",
      card2Text: "Explicitly allow bots like Google-Extended to ensure your site appears in AI Overviews.",
      howItWorksTitle: "Key Directives for AI",
      howItWorksP1: "Modern AI web crawlers look for specific User-agent strings:",
      points: [
        { title: "Google-Extended", desc: "Used for Google's AI Overviews and Gemini training." },
        { title: "GPTBot", desc: "OpenAI's primary crawler for ChatGPT." },
        { title: "ClaudeBot", desc: "Anthropic's crawler for Claude AI." }
      ]
    },
    useCases: [
      { icon: "Code2", title: "Developers", desc: "Protect API routes and admin panels from aggressive scraping." },
      { icon: "Building2", title: "Publishers", desc: "Control whether your content is used to train AI models." },
      { icon: "Search", title: "SEO Experts", desc: "Optimize your site for Generative Engine Optimization (GEO)." },
      { icon: "Users", title: "Bloggers", desc: "Ensure your latest posts are crawled by ChatGPT and Perplexity." }
    ],
    faqs: [
      { question: "Should I block all AI bots?", answer: "No. If you want your site to appear in AI search results (like ChatGPT or Perplexity), you must allow their bots." },
      { question: "Does blocking GPTBot stop ChatGPT from linking to me?", answer: "Yes, if you block GPTBot or OAI-SearchBot, ChatGPT will not be able to browse your site to provide real-time answers." },
      { question: "What is Crawl-delay?", answer: "It tells aggressive bots to wait a few seconds between requests to prevent server overload." }
    ]
  };

  const [allowAi, setAllowAi] = useState(true);
  const [blockAggressive, setBlockAggressive] = useState(true);
  const [sitemap, setSitemap] = useState('');
  const [llmstxt, setLlmstxt] = useState(true);
  const [disallowPaths, setDisallowPaths] = useState('/admin\n/private\n/*?*');
  
  const [generatedText, setGeneratedText] = useState('');

  useEffect(() => {
    let txt = `# ==========================================\n`;
    txt += `# Advanced robots.txt\n`;
    txt += `# Generated by LLMS.TXT Analyzer\n`;
    txt += `# ==========================================\n\n`;

    // Global
    txt += `# 1. Primary Search Engines\n`;
    txt += `User-agent: *\n`;
    txt += `Allow: /\n`;
    
    const paths = disallowPaths.split('\n').filter(p => p.trim() !== '');
    paths.forEach(p => {
      txt += `Disallow: ${p.trim()}\n`;
    });
    txt += `\n`;

    // AI Bots
    txt += `# 2. AI & LLM Crawlers\n`;
    const aiBots = ['Google-Extended', 'GPTBot', 'ChatGPT-User', 'OAI-SearchBot', 'PerplexityBot', 'Anthropic-ai', 'ClaudeBot', 'cohere-ai', 'OmgiliBot', 'Omgili', 'Applebot-Extended', 'Bytespider'];
    
    aiBots.forEach(bot => {
      txt += `User-agent: ${bot}\n`;
      txt += allowAi ? `Allow: /\n` : `Disallow: /\n`;
      if (allowAi) {
        paths.forEach(p => {
          txt += `Disallow: ${p.trim()}\n`;
        });
      }
      txt += `\n`;
    });

    // Aggressive Bots
    if (blockAggressive) {
      txt += `# 3. Aggressive/Low-Value Bots\n`;
      txt += `User-agent: Baiduspider\nCrawl-delay: 10\n\n`;
      txt += `User-agent: YandexBot\nCrawl-delay: 10\n\n`;
    }

    // Sitemaps
    if (sitemap || llmstxt) {
      txt += `# 4. Sitemaps & Semantic Web\n`;
      if (sitemap) {
        txt += `Sitemap: ${sitemap.trim()}\n`;
      }
      if (llmstxt) {
        txt += `Allow: /llms.txt\n`;
        txt += `Allow: /llms-full.txt\n`;
      }
    }

    setGeneratedText(txt);
  }, [allowAi, blockAggressive, sitemap, llmstxt, disallowPaths]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generatedText).then(() => {
      alert("robots.txt copied to clipboard!");
    });
  };

  const downloadTxt = () => {
    const element = document.createElement("a");
    const file = new Blob([generatedText], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "robots.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <>
    <div className="max-w-7xl mx-auto px-4 py-8">
      <div className="mb-10 text-center">
        <h1 className="text-3xl md:text-4xl font-bold text-slate-900 mb-4">{toolData.heroTitle}</h1>
        <p className="text-slate-600 max-w-2xl mx-auto">{toolData.heroSubtitle}</p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8 items-start">
        {/* Input Form */}
        <div className="glass-panel p-6 rounded-2xl space-y-6">
          
          {/* AI Settings */}
          <div className="bg-blue-50 border border-blue-200 p-5 rounded-2xl">
            <h3 className="font-bold text-blue-900 mb-3 flex items-center gap-2"><Bot className="w-5 h-5"/> AI Crawler Settings</h3>
            <div className="space-y-4">
              <label className="flex items-start gap-3 cursor-pointer">
                <input type="checkbox" checked={allowAi} onChange={(e) => setAllowAi(e.target.checked)} className="mt-1 w-5 h-5 text-blue-600 rounded border-slate-300 focus:ring-blue-500" />
                <div>
                  <span className="block font-bold text-slate-800">Allow Major AI Crawlers (Recommended)</span>
                  <span className="text-xs text-slate-600">Explicitly allows ChatGPT, Claude, Perplexity, and Google AI Overviews to crawl your site.</span>
                </div>
              </label>

              <label className="flex items-start gap-3 cursor-pointer">
                <input type="checkbox" checked={llmstxt} onChange={(e) => setLlmstxt(e.target.checked)} className="mt-1 w-5 h-5 text-blue-600 rounded border-slate-300 focus:ring-blue-500" />
                <div>
                  <span className="block font-bold text-slate-800">Expose llms.txt</span>
                  <span className="text-xs text-slate-600">Adds an explicit allow rule for /llms.txt at the bottom of the file.</span>
                </div>
              </label>
            </div>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Disallow Paths (One per line)</label>
              <textarea 
                value={disallowPaths} 
                onChange={(e) => setDisallowPaths(e.target.value)} 
                rows="4" 
                placeholder="/admin&#10;/private&#10;/temp" 
                className="w-full glass-input rounded-xl px-4 py-3 text-slate-900 font-mono text-sm outline-none resize-none"
              ></textarea>
              <p className="text-xs text-slate-500 mt-1">These paths will be blocked for ALL crawlers.</p>
            </div>

            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Sitemap URL (Optional)</label>
              <input 
                type="url" 
                value={sitemap} 
                onChange={(e) => setSitemap(e.target.value)} 
                placeholder="https://yoursite.com/sitemap.xml" 
                className="w-full glass-input rounded-xl px-4 py-3 text-slate-900 outline-none" 
              />
            </div>
            
            <label className="flex items-start gap-3 cursor-pointer bg-white/60 dark:bg-slate-800/50 p-4 rounded-xl border border-slate-200">
              <input type="checkbox" checked={blockAggressive} onChange={(e) => setBlockAggressive(e.target.checked)} className="mt-1 w-5 h-5 text-rose-600 rounded border-slate-300 focus:ring-rose-500" />
              <div>
                <span className="block font-bold text-slate-800">Throttled Aggressive Bots</span>
                <span className="text-xs text-slate-600">Adds a Crawl-delay for aggressive bots like Baiduspider and YandexBot to save server bandwidth.</span>
              </div>
            </label>
          </div>

        </div>

        {/* Live Preview */}
        <div className="sticky top-24 space-y-4">
          <div className="bg-slate-900 rounded-2xl shadow-xl overflow-hidden text-slate-300">
            <div className="bg-slate-800 px-4 py-2 border-b border-slate-700 flex justify-between items-center">
              <span className="text-xs font-mono text-slate-400">robots.txt</span>
              <div className="flex gap-2">
                <div className="w-3 h-3 rounded-full bg-rose-500"></div>
                <div className="w-3 h-3 rounded-full bg-amber-500"></div>
                <div className="w-3 h-3 rounded-full bg-emerald-500"></div>
              </div>
            </div>
            <div className="p-6 h-[450px] overflow-y-auto custom-scrollbar">
              <pre className="font-mono text-sm whitespace-pre-wrap leading-relaxed text-blue-300">
                {generatedText}
              </pre>
            </div>
          </div>
          
          <div className="flex gap-4">
            <button onClick={copyToClipboard} className="flex-1 flex justify-center items-center gap-2 glass-input bg-white text-slate-700 px-4 py-4 rounded-xl font-bold transition-colors">
              <Copy className="w-5 h-5" /> Copy Text
            </button>
            <button onClick={downloadTxt} className="flex-1 flex justify-center items-center gap-2 glass-button-primary px-4 py-4 rounded-xl font-bold transition-colors shadow-lg">
              <Download className="w-5 h-5" /> Download .txt
            </button>
          </div>
        </div>
      </div>
    </div>
    
    <ToolSEOContent 
      toolName={toolData.toolName}
      steps={toolData.steps}
      whatIs={toolData.whatIs}
      useCases={toolData.useCases}
      faqs={toolData.faqs}
    />
    </>
  );
};

export default RobotsTxtGenerator;
