import React from 'react';

const Terms = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <h1 className="text-4xl font-bold text-slate-900 mb-8">Terms of Service</h1>
      
      <div className="glass-panel p-8 rounded-2xl space-y-8 text-slate-700 leading-relaxed">
        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing and using the tools provided on LLMS.TXT Analyzer (the "Platform"), you accept and agree to be bound by the terms and provision of this agreement. 
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Document Generation Disclaimer</h2>
          <p className="mb-3">
            The documents generated by our platform (such as Rent Agreements, Leave Applications, and Salary Slips) are generated algorithmically based on user input. <strong>They are intended for informational and drafting purposes only.</strong>
          </p>
          <p>
            The Platform does not provide legal, financial, or tax advice. You are solely responsible for ensuring that any generated document complies with local, state, and national laws. We highly recommend consulting a certified professional (such as a lawyer or accountant) before executing any legal document.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Data Privacy and Local Storage</h2>
          <p>
            All tool calculations and document generations occur primarily in your local browser environment. We do not persistently store sensitive data inputted into our generators (such as personal addresses, salary figures, or signatures) on our servers unless explicitly stated for specific saved sessions. For more details, refer to our Privacy Policy.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">4. Usage Restrictions</h2>
          <p>
            You agree not to use the Platform for any unlawful purpose or to generate documents intended for fraudulent activities. The Platform and its tools are provided "as is" without any warranties of any kind.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-slate-900 mb-4">5. Limitation of Liability</h2>
          <p>
            In no event shall the Platform, its developers, or its affiliates be liable for any direct, indirect, incidental, special, or consequential damages arising out of or in any way connected with the use of the tools or documents generated herein.
          </p>
        </section>
      </div>
    </div>
  );
};

export default Terms;
